### ISSUE TITLE
Issues with platform handling in resolve_composes

### ISSUE THREAD

**Issue by owtaylor** [containerbuildsystem/atomic-reactor#1120]
Noticed the following when fixing up resolve_module_compose for multi-arch.

* `render_modules_request()` doesn't include the architecture
* `render_modules_request()` uses the result of util.get_platforms() as arches, but that is a set, and ODCSClient.start_compose() expects a list

**Comment by twaugh** [comment]
Owen, are you working on a fix for this?

**Comment by owtaylor** [comment]
No, I wasn't planning to work on this. I found these issues when using this
code as the basis for similar functionality in resolve_module_compose.

**Comment by twaugh** [comment]
OK. And the 'arches' issue relates to `render_packages_request()` I think?

**Comment by owtaylor** [comment]
> OK. And the 'arches' issue relates to `render_packages_request()` I think?

Yes - my comment makes more sense that way :-)

I think there's another issue here - because composes are triggered *separately* from the orchestrator and the workers, the fact that util.get_platforms() returns None for a worker build, will mean that worker builds end with composes for the default x86_64. (#1127 was that for Flatpaks the compose IDs weren't passed correctly to the workers, but here there doesn't even be an intent to pass them to the workers.) I might be missing something, but some investigation/testing of those code paths could be useful.

**Comment by lcarva** [comment]
Fixed by https://github.com/containerbuildsystem/atomic-reactor/commit/6b86ef6bcb75eaf22fb830193214120e16ac27c3
