### ISSUE TITLE
Record fetch archive information in build metadata

### ISSUE THREAD

**Issue by obriencj** [containerbuildsystem/atomic-reactor#1435]
The `fetch-archive-url.yaml` and `fetch-archive-koji.yaml` configurations should be represented in the build metadata.

Right now there appears to be no indication of the link between the resulting build and any archives. In particular, it would be great if we could easily identify that particular build NVRs (via the `fetch-archive-koji.yaml`) have become components of the container build.

**Comment by MartinBasti** [comment]
Thank you for opening issue. Team will discuss/design this and we will reach you. Please give us time :)

**Comment by obriencj** [comment]
Thanks. Ideally this information would be used to help in preventing component builds from being garbage collected by koji (ie. we could use the information to ensure that shipped containers have those builds safely tagged)

**Comment by obriencj** [comment]
I went digging a little bit just for my own enlightenment in how atomic_reactor deals with the data. 

It looks like right now in `inner.py` the results of the `PreBuildPluginRunner` `run()` method are just being discarded [1]. I think collecting those results, plus augmenting the `run()` results of `FetchMavenArtifactsPlugin` to record more of the original input rather than just the final fetch URLs (`process_by_nvr` and `process_by_url` could return more detailed and structured info, essentially)

[1]: https://github.com/containerbuildsystem/atomic-reactor/blob/master/atomic_reactor/inner.py#L500

**Comment by obriencj** [comment]
nope, working backwards from the code that utilized the yaml had me barking up the wrong tree, as those results don't end up where I thought they would. Looks like it's all constructed in the exit_koji_import.py -- so I guess that's a perfect spot to check for and load those yaml files.

(Hope you don't mind me logging my thoughts here as I have them, I'm just interested in seeing how these layers come together to make atomic work)

**Comment by lcarva** [comment]
Fixed by https://github.com/containerbuildsystem/atomic-reactor/commit/061d92e63cf27ae030e8ceed388ec34f51afb17b
