### ISSUE TITLE
deprecate "additional-tags" file

### ISSUE THREAD

**Issue by ktdreyer** [containerbuildsystem/atomic-reactor#1466]
There are two ways to set additional tags on a build:

A) Developers write tags into an `additional-tags` text file
B) Developers set the "tags" section of `container.yaml`

This is too complex for new OSBS users. If we're hard-coding version numbers, it's too easy to forget to bump the version numbers inside these tags.

Here are the problems with this approach:

1. The OSBS documentation does not specifically say that `additional-tags` is deprecated, and users copy-and-paste the pattern from dist-git repositories they've found elsewhere.

2. Developers mentally think of the settings in the `container.yaml` file. Developers easily forget to look at an additional file in the tree for additional settings. Developers only perform their overall "version-bumping" checklist once or twice a year, and that overall process is already incredibly complex. When we add even more files to bump, it's easier to make mistakes.

3. There is no way to recover from a mistake. If I've accidentally forgotten to bump version numbers in the `additional-tags` file, whoops, that tag is there in the registry forever. Contrast this with the way that I can `koji tag-build` or `koji untag-build` for Koji's tags, or even tag or untag builds I do myself on quay.io.

I think the solution is to deprecate the "additional-tags" file in our documentation, warn in the build logs for a deprecation period, and then stop reading `additional-tags` altogether.

**Comment by athos-ribeiro** [comment]
The way `additional-tags` are handled differs from what is done for the `tags` section in the `container.yaml` file.

while the tags in `additional-tags` are just additional tags that will be applied in the new image, tags in the `container.yaml` file will override the floating tags. In other words, the version and `latest` tags are implicitly applied in the first, but not in the latter.

I agree this is confusing and that we should deprecate the additional-tags file. But we should make sure we would not introduce issues for the users in the process. OSBS logs are quite extensive and if I had to guess, I'd say a considerable amount of users do not go through the logs of successful builds (they would not get the deprecation warning).

In this case, we would need to add the deprecation warning *and* tell OSBS downstream admins to announce it to their users in advance (e.g., sending emails, inspecting dist-git repos, mass PRs with fixes, etc).

**Comment by ktdreyer** [comment]
Thanks!

Mass PRs is an interesting idea. We do that kind of large cleanup often in Fedora for RPMs (eg. [removing the "Group" tag](https://fedoraproject.org/wiki/Changes/Remove_Group_Tag)). It would be interesting to build some kind of dynamic linter tool like stickler-ci.com that can "clean up" repositories as users initiate builds in OSBS, so that we only have to touch branches that developers are actively building.

**Comment by yazug** [comment]
OpenStack uses additional-tags to allow a series of images to be built together.  Use of tag in additional-tags for all images and then update the FROM to match the same tag.  Then when it builds it will pick up the same series of images, regardless of what other builds have been run for same namespace and floating tags.  This would introduce a bit more churn in a yaml file but at the end of the day still get same behavior with a possible additional entry we have to double maintain for  the same behavior.

**Comment by lcarva** [comment]
Deprecated here https://github.com/containerbuildsystem/atomic-reactor/commit/a19569b31f4f6d35bf33cbb0a9712e6517585268
