### ISSUE TITLE
RFE: expose valid signing_intent choices to clients

### ISSUE THREAD

**Issue by ktdreyer** [containerbuildsystem/atomic-reactor#1552]
Clients can send a `signing_intent` argument to buildContainer tasks. Is there any way for clients programmatically discover a list of valid options for that field?

I see the signing intents are defined in https://osbs.readthedocs.io/en/latest/admins.html#server-side-configuration-for-atomic-reactor , but is there any way for me to read that information as a non-administrator client?

The rpkg CLI has a `--signing-intent` argument, but `rpkg container-build --help` does not show the list of possible choices.

`koji --noauth call system.methodHelp buildContainer` gives me the API doc for the buildContainer task, but that text says to read `builder_containerbuild.py`. The JSON Schema in `PARAMS_SCHEMA` in that file says:

```python
"signing_intent": {
    "type": ["string", "null"],
    "description": "Signing intent of the ODCS composes."
},
```

So this string could be anything, and clients have to guess and check at the correct values, or learn it through some other form of tribal knowledge.

**Comment by MartinBasti** [comment]
I'd say it's tribal knowledge to know which signing intent to use. If non-existing `signing_intent` is used OSBS returns error with list of available signing intents.

Signing intents configuration is dynamic, each deployment may have different signing intents specified. Exposing this to CLI --help would be very complicated, it may require call to OSBS to lookup server side configuration. clients doesn't have direct access to OSBS server side, it has to be done via task via koji builder.

I'd say the best approach here is that OSBS administrators should provide a manual for users, which signing intents can be used and their meaning in the particular deployment.

**Comment by ktdreyer** [comment]
We chatted more about this. There are two human processes here: 1) administrators must manually update that documentation 2) users must manually search for the relevant documentation with the correct search engine.

My idea with this particular RFE is that the tools themselves could be more self-documenting. `--help` would never replace an entire user guide, but it would offer users more clues.

**Comment by ktdreyer** [comment]
Looks like we log `REACTOR_CONFIG` in `orchestrator.log` , and that contains the full list of `signing_intents` as configured on the server.

**Comment by lcarva** [comment]
> Looks like we log the `REACTOR_CONFIG` and `USER_PARAMS` environment variables in `orchestrator.log` , and that contains the full list of `signing_intents` as configured on the server.

@ktdreyer, does this address your request?

**Comment by ktdreyer** [comment]
And I put this into rpkg' `--help` text also, https://pagure.io/rpkg/pull-request/565
