### ISSUE TITLE
RFE: PrePublishSquashPlugin: make storing metadata possible with dont_load=false

### ISSUE THREAD

**Issue by pbabinca** [containerbuildsystem/atomic-reactor#163]
I believe squash plugin should always store metadata even if it doesn't load it back to docker.

**Comment by jpopelka** [comment]
AFAIK the `docker-scripts squash` by default (if --output-path isn't specified) doesn't create the tarball, so by default we have no file to get metadata about after squashing.

**Comment by TomasTomecek** [comment]
Exactly as Jirka says. When squashed image is loaded, we should use the updated image in engine.

**Comment by TomasTomecek** [comment]
Okay so... When loading image back to engine, we should export it and store it somewhere and of course, process the metadata.

**Comment by lcarva** [comment]
Closing due to lack of interest and activity. If you're still interested feel free to reopen it.
