### ISSUE TITLE
enable pushing images to docker hub

### ISSUE THREAD

**Issue by TomasTomecek** [containerbuildsystem/atomic-reactor#187]
Fedora will need this:

https://fedoraproject.org/wiki/Changes/Layered_Docker_Image_Build_Service/RACI
https://fedoraproject.org/wiki/Changes/Layered_Docker_Image_Build_Service

**Comment by jpopelka** [comment]
I can see 2 problems when pushing to `registry-1.docker.io`.

a) `docker.errors.APIError: 403 Client Error: Forbidden ("Error: Status 403 trying to push repository ... to official registry: needs to be forced")`

Work-around is to use docker RPM from [RHBZ#1224210](https://bugzilla.redhat.com/show_bug.cgi?id=1224210#c6)

b) We need to provide login credentials before pushing to docker hub.
One way is to have them stored in [~/.dockercfg](https://coreos.com/docs/launching-containers/building/registry-authentication/) or call [docker.Client().login(username="username", password="password", email="email")](https://docker-py.readthedocs.org/en/latest/api/#login).
We could have a prepublish plugin which would do that, but having the credentials stored in build json doesn't seem like a good idea to me.

**Comment by twaugh** [comment]
> b) We need to provide login credentials before pushing to docker hub.

If we could mount arbitrary Secrets volumes in build containers, I'd suggest that. I don't think that's possible though.

**Comment by TomasTomecek** [comment]
Indeed. Looks like we need to support 2 use cases:

1. standalone reactor
 1. mount `~/.dockercfg` inside build container
 2. take username and password as an cli argument
2. reactor in osbs
 1. take advantage of k8s secrets

**Comment by twaugh** [comment]
Example (from pulp plugin):
https://github.com/projectatomic/atomic-reactor/blob/master/atomic_reactor/plugins/post_push_to_pulp.py#L18-L43

**Comment by TomasTomecek** [comment]
Can we create the secret and link it to build in osbs-client?

**Comment by twaugh** [comment]
We can link it to a BuildConfig in osbs-client... that's what we already do.

As for creating the secret in osbs-client: we could do that, but it would mean putting the secret unencrypted in the HTTP request body.

**Comment by TomasTomecek** [comment]
Afaik all communication should go over https, so we should be fine, right?

**Comment by twaugh** [comment]
I guess so.

**Comment by twaugh** [comment]
Related:
  https://github.com/projectatomic/atomic-reactor/issues/404
  https://github.com/projectatomic/osbs-client/issues/335

**Comment by lcarva** [comment]
Closing due to lack of interest and activity. If you're still interested feel free to reopen it.
