### ISSUE TITLE
store decoded logs in build metadata (and make it configurable)

### ISSUE THREAD

**Issue by TomasTomecek** [containerbuildsystem/atomic-reactor#190]
\+ resolve this `FIXME` https://github.com/DBuildService/dock/blob/626314e8dea3078d2e034a8639245431280aa69b/dock/util.py#L325

**Comment by lcarva** [comment]
This is no longer relevant. `wait_for_command` is currently about 20 lines: https://github.com/containerbuildsystem/atomic-reactor/blob/134698cc09832d8d9618c68597c600c0ca0ad7e7/atomic_reactor/util.py
