### ISSUE TITLE
use `$name:latest` image tag when building an image

### ISSUE THREAD

**Issue by TomasTomecek** [containerbuildsystem/atomic-reactor#227]
b/c right now we use `$name/$component:unique-tag` and that's not something we may want when exporting image (that image name can be found in squashed & exported image)

I guess this should be configurable. @projectatomic/build-service-admins-committers @pbabinca thoughts?

**Comment by lcarva** [comment]
At the moment the repo is defined by the `name` label, and the tags can be configured by users: https://osbs.readthedocs.io/en/latest/users.html?highlight=tags#image-tags

Closing this issue.
