### ISSUE TITLE
Plugins are not self-contained

### ISSUE THREAD

**Issue by twaugh** [containerbuildsystem/atomic-reactor#265]
To populate plugin configuration fields, osbs-client needs to know
- names of plugins
- what types of plugin they are (pre/post/etc)
- names of arguments they take
- what value to fill in

For example, `url` and `use_auth` for plugins wanting to use OSBS.

It would be great if plugins could be more self-contained, with osbs-client not needing to know this sort of thing.

**Comment by TomasTomecek** [comment]
So you would like to move some configuration and logic from osbs-client to reactor? I'm +1 on that: I feel like that updating build image is easier than updating osbs-client. And in the end, we would have all the logic and everything in reactor, while osbs-client would be pure client with pretty much no configuration.

**Comment by twaugh** [comment]
I think so, yes. The osbs-client could provide information about which plugins to run (or even naming a build profile) and variable substitution values, and atomic-reactor could take care of which arguments are supplied, which order to run plugins in, etc.

**Comment by twaugh** [comment]
Plugins now always run, and decide for themselves whether action is needed.
