### ISSUE TITLE
Fix dockpulp logging

### ISSUE THREAD

**Issue by midnightercz** [containerbuildsystem/atomic-reactor#271]
PulpPushPlugin has attribute for setup logging level for dockpulp logger, but way it does this is insufficient. Atomic-reactor only obtain logger with call setup_logger from dockpulp and then call logger.setLevel for ensure desired logging level for dockpulp logger. However logger in dockpulp is initialized with NullHandler by default and that's why, no matter what is logging level, it never produces any log message when it's used from atomic-reactor.

**Comment by bkabrda** [comment]
I'll fix this.

**Comment by bkabrda** [comment]
@midnightercz when you get around to test the dockpulp patch (now accepted), please either close this issue or report any further problems.

**Comment by lcarva** [comment]
atomic-reactor does not use dock-pulp anymore. Closing this issue.
