### ISSUE TITLE
travis enables you to use docker

### ISSUE THREAD

**Issue by TomasTomecek** [containerbuildsystem/atomic-reactor#290]
http://docs.travis-ci.com/user/docker/

we could run some of our tests without mocking docker; not sure about which version of docker travis provides (it would be awesome, to have multiple versions of docker & docker-py)

**Comment by lcarva** [comment]
We don't use travis anymore. We use github actions. 

Closing this because running against docker/podman can be better handled in integration tests, removing some of the complexity in the unit tests.
