### ISSUE TITLE
Better binding between repository definitions and content

### ISSUE THREAD

**Issue by cgwalters** [containerbuildsystem/atomic-reactor#299]
For rpm-ostree, we encourage a model where a git repository stores both the equivalent of Dockerfile as well as the rpm-md `.repo` files.

atomic-reactor seems to take the .repos on the command line as a URL.  Unless the build system is in control over that URL, reproducibility goes out the window.  (Yes, I can find the URL from the build log, but it might change or go away, if it's e.g. stored in someone's Dropbox or whatever)

How about a model where the repositories are handled via ADD or something in `Dockerfile`, _but_ they can be overridden as well by the build system based on repo ID?  (I may commit a .repo file for centos-7 into my git, but a production build system would want to override that with a URL to its local cache)

**Comment by TomasTomecek** [comment]
I'm sorry but I don't follow. Could you please provide an example?

**Comment by cgwalters** [comment]
At my employer we have a deployment of atomic-reactor, and we also have an internal file server http://people.example.com/~user.  A person doing a build uploaded a `foo.repo` file to http://people.example.com/~user/foo.repo, and did a build from there.

But the release engineering infrastructure isn't in control over that location.  It could change, be deleted etc. at any time by the builder.  That harms reproducibility.

At least I think the input .repo file should be expanded in the logs and/or exposed by the Koji task frontend as an artifact.

Even better would be requiring the.repo file to live in the same git repository as the Dockerfile, so they're both owned by the rel-eng infrastructure.

**Comment by TomasTomecek** [comment]
The reason we chose currently implemented solution is that koji verifies that all packages present in an image were built in koji (rpmqa plugin) and then koji verifies that those are signed with proper keys. Therefore we don't care about repos, we care about packages.

Also, this doesn't force you to use this feature. You can store the repo in git and then `ADD` it within dockerfile.

> At least I think the input .repo file should be expanded in the logs and/or exposed by the Koji task
> frontend as an artifact.

Very good suggestion, will do.

@pbabinca wanna weigh in?

**Comment by lcarva** [comment]
It looks like logging the repo content is already handled.

Closing due to lack of interest and activity on the remaining of the request. If you're still interested feel free to reopen it.
