### ISSUE TITLE
improve docs!

### ISSUE THREAD

**Issue by TomasTomecek** [containerbuildsystem/atomic-reactor#36]
- [ ] main readme
  - [x] features
  - [x] installation
  - [ ] usage
    - [ ] build here
    - [ ] build inside build container
- [x] create separate dir for docs
- [ ] one document for plugins
  - [x] guide for writing plugins
  - [x] describe plugins
  - [ ] list best plugins
- [ ] python code (generate it)
  - [x] api.py
  - [x] tasker
  - [x] builder
  - [x] workflow
  - [ ] link with plugin development

**Comment by lcarva** [comment]
We should continue to improve the documentation as we make code changes. No need for an issue tracker.
