### ISSUE TITLE
tag_and_push: fails silently with insecure registry

### ISSUE THREAD

**Issue by twaugh** [containerbuildsystem/atomic-reactor#372]
When pushing to an insecure registry that has not been declared with `--insecure-registry ...` in `/etc/sysconfig/docker`, but _has_ been marked with `insecure_registry=True` in the plugin configuration, the push will fail silently.

I'm pushing to a distribution instance, if that makes any difference.

**Comment by twaugh** [comment]
It looks like `docker.Client.push(insecure_registry=True)` has been non-functional since before July 20th: https://github.com/docker/docker-py/commit/33e1a58b6034f4b586a55b5b42e644c11c281d25.

So this issue is just the error reporting.

**Comment by mmilata** [comment]
Does this mean that we should also get rid of the insecure flag that we pass from OSBS config all the way to these methods? Or do we need it for older docker-py versions?

**Comment by twaugh** [comment]
Someone who knows docker-py better than I do should comment on whether there's a better way of doing it now, or if it is just not possible at the push() level.

**Comment by TomasTomecek** [comment]
looks like that `insecure-registry` is a global flag for daemon and the api call flag no longer ~~has any effect~~ exists; docker-py started deprecated it: https://github.com/docker/docker-py/blob/master/docker/api/image.py#L212

**Comment by twaugh** [comment]
There is still at least one place that needs to know whether to use http or https for registries: the `pulp_sync` plugin.

Aside from that, we should probably file an issue to track issuing a warning when it's seen in config, and removing it from calls that pass it around only to have it ultimately discarded. Need to take care to keep the API from breaking.

**Comment by twaugh** [comment]
Filed as https://github.com/projectatomic/atomic-reactor/issues/392.

**Comment by lcarva** [comment]
Closing due to lack of interest and activity. If you're still interested feel free to reopen it.
