### ISSUE TITLE
Remove/deprecate unused insecure_registry configuration

### ISSUE THREAD

**Issue by twaugh** [containerbuildsystem/atomic-reactor#392]
When pushing an image to a registry, the docker-py call discards the `insecure_registry` parameter.

Given that, we should:
- issue a warning when it's seen in config
- remove it from calls that pass it around only to have it ultimately discarded

Need to take care to keep the API from breaking.

**Comment by TomasTomecek** [comment]
Totally agree; we should do this sooner rather than later.

**Comment by mmilata** [comment]
Looks like the version in current RHEL7 (`python-docker-py-1.4.0-118.el7.noarch`) uses the parameter to decide whether to use http/https. It's weird because upstream 1.4.0 dropped it but what's in RHEL is different from upstream 1.4.0. I'd wait for RHEL to ship newer version before doing this.

**Comment by TomasTomecek** [comment]
The issue is that docker-py in RHEL was built "kind of funky" -- release commit wasn't used, instead it was rebased and some "random" snapshot was promoted as a final build. Latest build should avoid this.

**Comment by lcarva** [comment]
The current usage of `insecure_registry` is in the ImageStreamTag objects which is still relevant. We no longer use this config parameter when using docker-py.
