### ISSUE TITLE
List of repositories where image was pushed has incorrect registry

### ISSUE THREAD

**Issue by pbabinca** [containerbuildsystem/atomic-reactor#408]
I'm using osbs-client to submit build in atomic reactor. Snippet of osbs.conf:

```
[default]
openshift_uri = https://openshift-builder:9443/
koji_root = http://kojiweb/kojifiles
koji_hub = http://kojihub/koji
sources_command = rpkg sources
registry_uri = registry:8888
build_type = prod-with-secret
source_secret = pulpsecret
pulp_registry_name = default-qa
```

dockpulp is used to push the content. Snippet of dockpulp.conf:

```
[pulps]
default-qa = https://registry
[registries]
default-qa = https://registry/v1/repositories
[filers]
brew-qa = http://registry
```

After successful build atomic reactor returned wrong docker repository URL. Instead of `registry:8888/repo` it returned `registry/repo`. I'm not sure if it just removed port part from `registry_uri` or used Pulp's hostname.

I'm using this output to indicate where the image was pushed and I need `registry_uri` for this.

I'm using `atomic-reactor-1.6.1-1`.

**Comment by twaugh** [comment]
I wonder if `source_registry_uri` is getting initialized to a incorrect value when not explicitly set.

**Comment by TomasTomecek** [comment]
logs should contain whole `conf`, right?

**Comment by twaugh** [comment]
Actually I think `dockpulp.conf` should have a different value for the `registries` section. It should be `https://registry:8888/v1/repositories`.

It takes the hostname and port from that value.

**Comment by lcarva** [comment]
Pulp integration has been removed from atomic-reactor. Dropping this.
