### ISSUE TITLE
create local commit hook

### ISSUE THREAD

**Issue by TomasTomecek** [containerbuildsystem/atomic-reactor#42]
regen docs when api changes
- [ ] manpage
- [ ] api

**Comment by lcarva** [comment]
Let's consider using something more automatic such as read the docs with sphinx.

**Comment by TomasTomecek** [comment]
Feel free to close this and create a new one for sphinx.

**Comment by lcarva** [comment]
Closing this. Documentation is automatically generated in the osbs-docs project.
