### ISSUE TITLE
Set DOCKER_TIMEOUT for squashing

### ISSUE THREAD

**Issue by twaugh** [containerbuildsystem/atomic-reactor#429]
When squashing an image, the default docker-scripts timeout is 10 minutes. It would be nice to be able to tweak that as needed, by setting the DOCKER_TIMEOUT environment variable from a configuration setting.

**Comment by TomasTomecek** [comment]
the easiest thing to do is probably tweak dockerfile of the build image

**Comment by lcarva** [comment]
Closing due to lack of interest and activity. If you're still interested feel free to reopen it.

Also, the plan is to move away from docker completely.
