### ISSUE TITLE
Build build images at docker hub 

### ISSUE THREAD

**Issue by TomasTomecek** [containerbuildsystem/atomic-reactor#44]

**Comment by bkabrda** [comment]
So, the images are now built under https://registry.hub.docker.com/u/slavek/atomic-reactor/. I'll try to see what it'd take to build them under projectatomic namespace.

**Comment by lcarva** [comment]
I'm wondering if pushing images to dockerhub will actually benefit anyone. From what I understand, fedora maintains its own buildroot.

**Comment by TomasTomecek** [comment]
This was meant to be for anyone who would like to use this project.

**Comment by lcarva** [comment]
Closing this as there hasn't been any interest in using a container image with just atomic-reactor in docker hub.
