### ISSUE TITLE
plugins: figure out OSv3 builder URL automatically

### ISSUE THREAD

**Issue by mmilata** [containerbuildsystem/atomic-reactor#440]
We should be able to extract it from build JSON.

Plugins:
- koji_promote
- sendmail
- import_image
- store_metadata_in_osv3
- check_and_set_rebuild

**Comment by mmilata** [comment]
It's not in the build JSON but should be discoverable through evironment variables. However on my test VM I have

    KUBERNETES_SERVICE_HOST="172.30.0.1"
    KUBERNETES_SERVICE_PORT="443"

which doesn't seem right - looks like address range of the OpenShift SDN which we currently don't use.

**Comment by vrutkovs** [comment]
AFAIK only services (which require SDN) are set as env vars, so its not gonna be easy to get openshift url without them.

On the other hand we might want to introduce SDN in order to support openshift services (e.g. ElasticSearch and Kibana)

**Comment by lcarva** [comment]
Closing due to lack of interest and activity. If you're still interested feel free to reopen it.
