### ISSUE TITLE
Run some plugins in parallel with each other

### ISSUE THREAD

**Issue by twaugh** [containerbuildsystem/atomic-reactor#460]
In #458, the pulp_push plugin and the compress plugin will be able to do their unrelated jobs in parallel with each other.

This will also be true for pulp_sync in the v2 workflow.

It could be a lot of work to implement this, so we should decide whether we really want to keep hold of the 'docker save' tarball at all before proceeding.

**Comment by MartinBasti** [comment]
Not worth to invest time into this. Longest time takes ODCS and cachito intgration
