### ISSUE TITLE
RFE: support bumping for major.minor format of release tag

### ISSUE THREAD

**Issue by hhorak** [containerbuildsystem/atomic-reactor#474]
Method `get_next_release` in `atomic_reactor/plugins/pre_bump_release.py` is incrementing first digit. I think that this is not ideal, because if anybody uses `major.minor` format, rebuild should only increment the minor number -- that was what I would expect.

A real use case for this is the following: Development team releases image with release 5. Then, the development continues and maintainers increase the release number and rebuild as they wish. New images then have release 6, 7, 8, ... When an automatic rebuild is needed, the currently released image is bumped, so rebuilt image should have 6, but such image already exists. If only minor number is added/bumped, we won't have problems with conflicts and rebuilds will always be recognized easily from newer releases.

**Comment by twaugh** [comment]
CC @soltysh

**Comment by lcarva** [comment]
Closing due to lack of interest and activity. If you're still interested feel free to reopen it.
