### ISSUE TITLE
Update spec file

### ISSUE THREAD

**Issue by vrutkovs** [containerbuildsystem/atomic-reactor#542]
- Don't use 'spec: update hash for <version>' commits - specify tag instead of the commit hash.
  This way we can point to a specific tag in one commit:

```
URL:            https://github.com/projectatomic/%{project}
Source0: %{url}/archive/%{version}/%{name}-%{version}.tar.gz
```
- Consider using a separate python file with version: `version.py` (see [Marek's Docker Squash](https://github.com/goldmann/docker-squash/blob/master/docker_squash/version.py))
- `BuildRequires: git` is too inclusive - `git-core` should be sufficient

**Comment by twaugh** [comment]
The reason we use the git hash is that git tags are mutable whereas git hashes are not.

**Comment by lcarva** [comment]
This has been fixed by https://github.com/containerbuildsystem/atomic-reactor/commit/c1885c2e161a691d198e1ea6c5a3af7009235260
