### ISSUE TITLE
Run 'yum clean all' in the end of the build stage

### ISSUE THREAD

**Issue by vrutkovs** [containerbuildsystem/atomic-reactor#576]
Yum cache files are not needed in the built container. Running 'yum clean all' is a recommended step and should help with trimming image size

**Comment by lcarva** [comment]
Could this be part of best practices guidelines, instead of enforcing it via code?

**Comment by vrutkovs** [comment]
I haven't seen a single container (*cough* osbs-buildroot-docker *cough*) which actually does that. Perhaps people expect squash to trim the size, which was never intended to do that.

**Comment by vrutkovs** [comment]
Tested on osbs-buildroot-docker: shaved off 30 MBs out of original 448.7 MB

**Comment by lcarva** [comment]
This has been implemented as static analysis checks outside of OSBS which is probably safer than doing this within OSBS.
