### ISSUE TITLE
atomic-container should cancel stuck builds

### ISSUE THREAD

**Issue by vrutkovs** [containerbuildsystem/atomic-reactor#579]
AR should stop the build if its stuck. 

Perhaps the safest way to detect that the build is stuck is switching docker-py's build in `build_image_from_path` to stream mode and stop the build if there are no new messages in 10 minutes

**Comment by twaugh** [comment]
I would much rather this was signal-driven. It should be part of handling the signal used to stop the container when the build is cancelled.

Once that basic mechanism is working, we could potentially think about putting a time-out on build output (but in that case I would rather it was several hours than ten minutes).

**Comment by vrutkovs** [comment]
It seems the created container is being removed correctly if the build is cancelled. Running exit plugins would be a good idea though

**Comment by lcarva** [comment]
Closing due to lack of interest and activity. If you're still interested feel free to reopen it.
