### ISSUE TITLE
exit_koji_promote: support optional component parameter

### ISSUE THREAD

**Issue by twaugh** [containerbuildsystem/atomic-reactor#580]
The Koji component ought to be possible to pass in as a parameter. When koji-containerbuild uses osbs-client to submit a build it already passes in the component name from the git repository used.

If osbs-client could instruct exit_koji_promote to use this value we would not need to examine the com.redhat.component label in the Dockerfile.

**Comment by lcarva** [comment]
Should there be some sort of verification for `--component` and `com.redhat.component` values?

**Comment by twaugh** [comment]
I think there should not. I think OSBS should act independently of what is set for `com.redhat.component`, allowing for this label to be unpinned from the Koji component used to upload builds.

**Comment by lcarva** [comment]
Wouldn't that cause confusion though? What's the use case for having two distinct components?
Maybe it should overwrite the label in the Dockerfile if `component` param is given.

My concern is that there are other plugins that also interact with Koji, bump_release for example.
It's not clear which component value will be used for each case.

**Comment by twaugh** [comment]
There is not always going to be a Bugzilla component for every image: some images are 'intermediate' and do not have their own component in the Bugzilla interface, but bugs in that image should be reported against some other component (i.e. one relating to a final shipped image which uses the intermediate image).

**Comment by lcarva** [comment]
Closing due to lack of interest and activity. If you're still interested feel free to reopen it.
