### ISSUE TITLE
use of force=True when removing docker objects

### ISSUE THREAD

**Issue by twaugh** [containerbuildsystem/atomic-reactor#659]
When removing images in exit_remove_built_image.py, 'force=True' is used.

Is this really correct? Could use of force lead to problems? See e.g. https://bugzilla.redhat.com/show_bug.cgi?id=1391665#c110

**Comment by vrutkovs** [comment]
`force=True` was introduce to make sure two builds on the same node don't block or fail when the same layer (e.g. a base image) is being requested to be removed twice.

Ideally docker-py should have `skip` param to ignore this situation

**Comment by lcarva** [comment]
Closing due to lack of interest and activity. If you're still interested feel free to reopen it.
