### ISSUE TITLE
Consistency in debug logging across modules

### ISSUE THREAD

**Issue by twaugh** [containerbuildsystem/atomic-reactor#679]
When the `--verbose` parameter is supplied, atomic-reactor and its plugins log at DEBUG level. However those plugins also use other modules such as osbs-client and dockpulp, and those modules continue to log at their default levels.

There should be a way to cause those modules to log at DEBUG level. Perhaps `--verbose` should cause that, or perhaps it should be a separate `--debug` parameter.

Implementation-wise, a DockerBuildWorkflow instance variable could hold the logging level to be used for modules-of-interest used by plugins, and plugins should inspect this instance variable and use it to set logging levels for those modules as appropriate.

*Alternatively*, those modules should inherit the logging level used by atomic-reactor.

**Comment by yahzaa** [comment]
I would like to work on this.

**Comment by lcarva** [comment]
Because of the large amount of logs osbs-client produces, it might be better to have separate parameter for osbs-client. It may expose things like auth token.

**Comment by lcarva** [comment]
Closing due to lack of interest and activity. If you're still interested feel free to reopen it.
