### ISSUE TITLE
Proposal: redesign atomic-reactor

### ISSUE THREAD

**Issue by TomasTomecek** [containerbuildsystem/atomic-reactor#85]
For quite some time, I think that dock's CLI, code and architecture is getting a bit messy. This is my proposal how we could improve it. We'll have a single command for building images, which will be `build`.
### Build Types

`build` will have subcommands called **build types** (there will be a default build type). We'll probably start with just one build type which will precisely match the current behaviour. Build types will be very similar to what osbs-client has. Build types will be predefined recipes how to build an image (and what plugins should be used) — json templates. Every build type will have a set of its own arguments. Most build types will have similar arguments e.g. `--image`.

We could possibly even improve the json to something like:

``` json
{
  "input": {
    "type": "path",
    "args": {
        "path": "/here/is/my/dockerfile"
    },
    "source_repository": "..."
  },
  "output": {
    "tag": {
      "value": "...",
      "repositories": [...]
    }
  },
  "plugins": ...
```
### Methods

Methods will work the same:
1. `--method privileged`
2. `--method docker-host` (every occurrence of `host.?docker` will be changed)
3. `--method local` (`dock local` could be symlink to `dock build --method local`)
### Input

When you specify build json on your own, build type will be ignored. You may be still able to override values in your json from CLI.

`--input` will be direct mapping for input plugins (getting build json from env var, path,...). You'll be able to override this via CLI.

If you don't care about code, you can stop reading.

In code, I would like to have a lot of changes too:
- start getting rid of `DockerBuildWorkflow` and moving logic to plugins
- `InsideBuilder` should be as light as possible
- I would like to see more classes rather than having one class accepting 15 arguments
- we need to figure what will be the best interface to configure plugins from CLI (`--substitute` might be enough)

CC @goldmann @mmilata @twaugh @jpopelka @l-d-j @adamruzicka

I really would like to hear your feedback on this.

**Comment by adamruzicka** [comment]
Will dock still have ```create-build-image``` and ```inside-build``` comands or will they be converted to build types?

Methods and Input looks good to me.
+1 for moving logic to plugins, making ```InsideBuilder``` lighter and splitting to more classes

**Comment by twaugh** [comment]
Looks good in general. How would plugins communicate with one another? Currently they store state in the `DockerBuildWorkflow` instance, don't they?

**Comment by TomasTomecek** [comment]
@adamruzicka 
`create-build-image` was done mainly to get latest dock inside build image. Since dock is already packaged I pretty much find this command deprecated and am favoring image creation using docker directly. This means that the command will work still and you shouldn't expect any changes & improvements. At some point, I would love to have build images on docker hub directly.

`inside-build` will be merged into `build local`: we should have only one method to build images in current env.

@twaugh 
Good question. Unless we come with some better solution, I would be in favor of having a class which will manage whole build (`D-B-Workflow` atm) and let plugins access an instance of the class -- current behavior.

**Comment by l-d-j** [comment]
this sounds great for me. I like the idea of one build command and custom recipes defining flow also with this approach dock can be used with rkt in future (if "docker build" will be plugin also). 
But this sounds little bit like general build tool similar to maven. If I map new dock plugins to phases then recipe file seems like pom.xml without many features. I don't know python ecosystem well but  maybe there is a some "build tool/simple workflow" management library we should extend same way?
Because in this approach a dock seems like a recipe runner which passes some instance object to plugins(to make them communicate) and execute them in a right order.

**Comment by TomasTomecek** [comment]
@l-d-j 
Essentially, yes. Unfortunately I'm not aware of any such framework in python. Will investigate.

**Comment by l-d-j** [comment]
@TomasTomecek   if there is not any (I didn't find something good too - everything seems complicated or just not nice to use) maybe dock can be separated to workflow layer and a "what dock is now" layer

**Comment by bkabrda** [comment]
@TomasTomecek so this would also mean merging `dock.inner.build_inside` and `dock.api.build_image_here`, is that correct? Because it seems that one of these is pretty much redundant and we could have one doing both (I think).

@l-d-j what would be the advantage of separating dock into workflow layer and "what dock is now"? Keeping both of these inside dock will make things a lot easier for us, IMHO.

**Comment by TomasTomecek** [comment]
> @TomasTomecek so this would also mean merging `dock.inner.build_inside` and `dock.api.build_image_here`, is that correct? Because it seems that one of these is pretty much redundant and we could have one doing both (I think).

That's exactly my point: have one command which builds images in current environment and have one piece of code to take care of that.

**Comment by lcarva** [comment]
Closing this because we have already modified atomic-reactor to use plugins for different workflows.
