### ISSUE TITLE
Consider using https://github.com/litl/backoff for retries

### ISSUE THREAD

**Issue by vrutkovs** [containerbuildsystem/atomic-reactor#875]
This lib seems to be implementing all retry strategies we want, so instead of custom handler it might be easier to package it in Fedora/RHEL and reuse it

**Comment by lcarva** [comment]
That does look pretty neat! I think it's a great long term approach.

**Comment by twaugh** [comment]
Does anything else already use litl/backoff? Wondering if this is the Python package to decide to package as RPM or if there's any other similar one.

**Comment by lcarva** [comment]
@MartinBasti, did you file an internal tracker for this?

**Comment by MartinBasti** [comment]
yes

**Comment by mkosiarc** [comment]
This was solved by https://github.com/containerbuildsystem/atomic-reactor/pull/1653
